"""SmartUp to Core Data Layer mapping registry."""

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SmartUpFieldMapping:
    """Maps one SmartUp field to one core field."""

    source_field: str
    target_field: str
    notes: str = ""


@dataclass(frozen=True, slots=True)
class SmartUpMapping:
    """Describes how a SmartUp endpoint maps into the core layer."""

    name: str
    group: str
    smartup_endpoint: str
    smartup_method: str
    smartup_object: str
    target_table: str
    target_entity: str
    sync_mode: str
    key_fields: tuple[str, ...]
    field_mappings: tuple[SmartUpFieldMapping, ...] = ()
    notes: tuple[str, ...] = ()


SMARTUP_CORE_MAPPING_V1: tuple[SmartUpMapping, ...] = (
    SmartUpMapping(
        name="Legal entities",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mr/legal_person$export",
        smartup_method="POST",
        smartup_object="legal_person",
        target_table="contacts",
        target_entity="Business / client company",
        sync_mode="incremental",
        key_fields=("person_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("person_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("name", "full_name"),
            SmartUpFieldMapping("short_name", "display_name"),
            SmartUpFieldMapping("address", "metadata.address"),
            SmartUpFieldMapping("main_phone", "phone"),
            SmartUpFieldMapping("email", "metadata.email"),
            SmartUpFieldMapping("tin", "metadata.tin"),
            SmartUpFieldMapping("state", "metadata.state"),
            SmartUpFieldMapping("groups", "metadata.groups"),
        ),
        notes=(
            "Primary source for legal counterparties and client companies.",
            "Use with natural persons to build a unified contact graph.",
        ),
    ),
    SmartUpMapping(
        name="Natural persons",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mr/natural_person$export",
        smartup_method="POST",
        smartup_object="natural_person",
        target_table="contacts",
        target_entity="Contact person",
        sync_mode="incremental",
        key_fields=("person_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("person_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("first_name", "metadata.first_name"),
            SmartUpFieldMapping("last_name", "metadata.last_name"),
            SmartUpFieldMapping("middle_name", "metadata.middle_name"),
            SmartUpFieldMapping("birthday", "metadata.birthday"),
            SmartUpFieldMapping("gender", "metadata.gender"),
            SmartUpFieldMapping("address", "metadata.address"),
            SmartUpFieldMapping("telegram", "metadata.telegram"),
            SmartUpFieldMapping("legal_person_code", "metadata.legal_person_code"),
        ),
        notes=("Primary source for individual contacts and people-related CRM data.",),
    ),
    SmartUpMapping(
        name="Inventory",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mr/inventory$export",
        smartup_method="POST",
        smartup_object="inventory",
        target_table="products",
        target_entity="Product / inventory item",
        sync_mode="incremental",
        key_fields=("product_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("product_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("name", "name"),
            SmartUpFieldMapping("short_name", "metadata.short_name"),
            SmartUpFieldMapping("measure_code", "metadata.measure_code"),
            SmartUpFieldMapping("producer_code", "metadata.producer_code"),
            SmartUpFieldMapping("gtin", "metadata.gtin"),
            SmartUpFieldMapping("ikpu", "metadata.ikpu"),
            SmartUpFieldMapping("tnved", "metadata.tnved"),
            SmartUpFieldMapping("inventory_kinds", "metadata.inventory_kinds"),
            SmartUpFieldMapping("groups", "metadata.groups"),
        ),
        notes=("Primary source for products, goods, raw materials and equipment catalog.",),
    ),
    SmartUpMapping(
        name="Product groups",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mr/product_group$export",
        smartup_method="POST",
        smartup_object="product_group",
        target_table="product_groups",
        target_entity="Product group",
        sync_mode="incremental",
        key_fields=("product_group_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("product_group_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("name", "name"),
            SmartUpFieldMapping("product_kind", "metadata.product_kind"),
            SmartUpFieldMapping("state", "metadata.state"),
            SmartUpFieldMapping("product_group_types", "metadata.product_group_types"),
        ),
    ),
    SmartUpMapping(
        name="Price types",
        group="master_data",
        smartup_endpoint="/b/anor/api/v2/mkr/price_type$export",
        smartup_method="POST",
        smartup_object="data",
        target_table="price_types",
        target_entity="Price type",
        sync_mode="incremental",
        key_fields=("code",),
        field_mappings=(
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("name", "name"),
            SmartUpFieldMapping("short_name", "metadata.short_name"),
            SmartUpFieldMapping("with_card", "metadata.with_card"),
            SmartUpFieldMapping("state", "metadata.state"),
            SmartUpFieldMapping("price_type_kind", "metadata.price_type_kind"),
            SmartUpFieldMapping("currency_code", "metadata.currency_code"),
        ),
    ),
    SmartUpMapping(
        name="Inventory prices",
        group="master_data",
        smartup_endpoint="/b/anor/api/v2/mkf/product_price$export",
        smartup_method="POST",
        smartup_object="inventory",
        target_table="price_points",
        target_entity="Inventory price",
        sync_mode="incremental",
        key_fields=("inventory_code", "price_type_code"),
        field_mappings=(
            SmartUpFieldMapping("inventory_code", "metadata.inventory_code"),
            SmartUpFieldMapping("inventory_barcode", "metadata.inventory_barcode"),
            SmartUpFieldMapping("price_type", "metadata.price_type"),
        ),
        notes=("This becomes price history and pricing lookup for analytics.",),
    ),
    SmartUpMapping(
        name="Producers",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mr/producer$export",
        smartup_method="POST",
        smartup_object="producer",
        target_table="producers",
        target_entity="Producer / supplier reference",
        sync_mode="incremental",
        key_fields=("person_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("person_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("name", "name"),
            SmartUpFieldMapping("short_name", "display_name"),
            SmartUpFieldMapping("state", "metadata.state"),
            SmartUpFieldMapping("groups", "metadata.groups"),
        ),
    ),
    SmartUpMapping(
        name="Contracts",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mkf/contract$export",
        smartup_method="POST",
        smartup_object="contract",
        target_table="contracts",
        target_entity="Contract",
        sync_mode="incremental",
        key_fields=("contract_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("contract_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("contract_type", "metadata.contract_type"),
            SmartUpFieldMapping("begin_contract_date", "metadata.begin_contract_date"),
            SmartUpFieldMapping("end_contract_date", "metadata.end_contract_date"),
            SmartUpFieldMapping("state", "metadata.state"),
        ),
    ),
    SmartUpMapping(
        name="Workspaces",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mrf/room$export",
        smartup_method="POST",
        smartup_object="room",
        target_table="workspaces",
        target_entity="Workspace / territory",
        sync_mode="incremental",
        key_fields=("room_id", "room_code"),
        field_mappings=(
            SmartUpFieldMapping("room_id", "external_ref"),
            SmartUpFieldMapping("room_code", "external_ref"),
            SmartUpFieldMapping("room_name", "name"),
            SmartUpFieldMapping("room_type_code", "metadata.room_type_code"),
            SmartUpFieldMapping("filial_code", "metadata.filial_code"),
            SmartUpFieldMapping("state", "metadata.state"),
        ),
    ),
    SmartUpMapping(
        name="Service export",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mr/service$export",
        smartup_method="POST",
        smartup_object="service",
        target_table="services",
        target_entity="Service / catalog item",
        sync_mode="incremental",
        key_fields=("service_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("service_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("name", "name"),
            SmartUpFieldMapping("short_name", "metadata.short_name"),
            SmartUpFieldMapping("state", "metadata.state"),
        ),
    ),
    SmartUpMapping(
        name="Person group export",
        group="master_data",
        smartup_endpoint="/b/anor/mxsx/mr/person_group$export",
        smartup_method="POST",
        smartup_object="person_group",
        target_table="person_groups",
        target_entity="Person group",
        sync_mode="incremental",
        key_fields=("person_group_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("person_group_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("name", "name"),
            SmartUpFieldMapping("state", "metadata.state"),
        ),
    ),
    SmartUpMapping(
        name="Orders",
        group="sales",
        smartup_endpoint="/b/trade/txs/tdeal/order$export",
        smartup_method="POST",
        smartup_object="order",
        target_table="sales",
        target_entity="Order / sale",
        sync_mode="incremental",
        key_fields=("deal_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("deal_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("person_code", "contact.external_ref"),
            SmartUpFieldMapping("sales_manager_code", "metadata.sales_manager_code"),
            SmartUpFieldMapping("room_code", "metadata.room_code"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("delivery_date", "metadata.delivery_date"),
            SmartUpFieldMapping("deal_time", "metadata.deal_time"),
            SmartUpFieldMapping("order_products", "metadata.line_items"),
            SmartUpFieldMapping("total_amount", "metadata.total_amount"),
        ),
        notes=("Use order lines as the primary sales fact for analytics and dashboard KPI.",),
    ),
    SmartUpMapping(
        name="Returns",
        group="sales",
        smartup_endpoint="/b/anor/mxsx/mdeal/return$export",
        smartup_method="POST",
        smartup_object="return",
        target_table="sales_returns",
        target_entity="Sales return",
        sync_mode="incremental",
        key_fields=("deal_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("deal_id", "sales_reference.external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("return_reason_code", "metadata.return_reason_code"),
            SmartUpFieldMapping("return_date", "metadata.return_date"),
            SmartUpFieldMapping("return_products", "metadata.line_items"),
        ),
    ),
    SmartUpMapping(
        name="Return reason export",
        group="sales",
        smartup_endpoint="/b/anor/mxsx/mdeal/return_reason$export",
        smartup_method="POST",
        smartup_object="return_reason",
        target_table="return_reasons",
        target_entity="Return reason",
        sync_mode="incremental",
        key_fields=("return_reason_id", "code"),
        field_mappings=(
            SmartUpFieldMapping("return_reason_id", "external_ref"),
            SmartUpFieldMapping("code", "external_ref"),
            SmartUpFieldMapping("name", "name"),
            SmartUpFieldMapping("state", "metadata.state"),
        ),
    ),
    SmartUpMapping(
        name="Client payments",
        group="finance",
        smartup_endpoint="/b/trade/txs/tcs/cashin$export",
        smartup_method="POST",
        smartup_object="cashin",
        target_table="payments",
        target_entity="Client payment",
        sync_mode="incremental",
        key_fields=("cashin_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("cashin_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("person_code", "contact.external_ref"),
            SmartUpFieldMapping("cashin_date", "occurred_at"),
            SmartUpFieldMapping("amount", "amount"),
            SmartUpFieldMapping("currency_code", "currency"),
            SmartUpFieldMapping("payment_type_code", "metadata.payment_type_code"),
        ),
    ),
    SmartUpMapping(
        name="Cash operations",
        group="finance",
        smartup_endpoint="/b/anor/mxsx/mkcs/cash_operation$export",
        smartup_method="POST",
        smartup_object="cash_operation",
        target_table="finance_entries",
        target_entity="Cash ledger entry",
        sync_mode="incremental",
        key_fields=("operation_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("operation_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("operation_date", "occurred_at"),
            SmartUpFieldMapping("amount", "amount"),
            SmartUpFieldMapping("currency_code", "currency"),
            SmartUpFieldMapping("operation_type", "metadata.operation_type"),
        ),
    ),
    SmartUpMapping(
        name="Bank statements",
        group="finance",
        smartup_endpoint="/b/anor/mxsx/mkcs/bank_operation$export",
        smartup_method="POST",
        smartup_object="bank_operation",
        target_table="finance_entries",
        target_entity="Bank ledger entry",
        sync_mode="incremental",
        key_fields=("operation_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("operation_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("operation_date", "occurred_at"),
            SmartUpFieldMapping("amount", "amount"),
            SmartUpFieldMapping("currency_code", "currency"),
            SmartUpFieldMapping("bank_account_code", "metadata.bank_account_code"),
        ),
    ),
    SmartUpMapping(
        name="Logistics export",
        group="operations",
        smartup_endpoint="/b/trade/txs/tdeal/logistics$export",
        smartup_method="POST",
        smartup_object="logistics",
        target_table="logistics",
        target_entity="Logistics",
        sync_mode="incremental",
        key_fields=("logistics_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("logistics_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Cross-organizational movement export",
        group="operations",
        smartup_endpoint="/b/anor/mxsx/mfm/movement$export",
        smartup_method="POST",
        smartup_object="movement",
        target_table="cross_organizational_movements",
        target_entity="Cross-organizational movement",
        sync_mode="incremental",
        key_fields=("movement_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("movement_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Internal movement export",
        group="operations",
        smartup_endpoint="/b/anor/mxsx/mkw/movement$export",
        smartup_method="POST",
        smartup_object="movement",
        target_table="internal_movements",
        target_entity="Internal movement",
        sync_mode="incremental",
        key_fields=("movement_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("movement_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Stocktaking export",
        group="operations",
        smartup_endpoint="/b/anor/mxsx/mkw/stocktaking$export",
        smartup_method="POST",
        smartup_object="stocktaking",
        target_table="stocktakings",
        target_entity="Stocktaking",
        sync_mode="incremental",
        key_fields=("stocktaking_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("stocktaking_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Write-off export",
        group="operations",
        smartup_endpoint="/b/anor/mxsx/mkw/writeoff$export",
        smartup_method="POST",
        smartup_object="writeoff",
        target_table="write_offs",
        target_entity="Write-off",
        sync_mode="incremental",
        key_fields=("writeoff_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("writeoff_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Return to suppliers export",
        group="operations",
        smartup_endpoint="/b/anor/mxsx/mkw/return$export",
        smartup_method="POST",
        smartup_object="return",
        target_table="supplier_returns",
        target_entity="Return to suppliers",
        sync_mode="incremental",
        key_fields=("return_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("return_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Receipts to warehouse export",
        group="operations",
        smartup_endpoint="/b/anor/mxsx/mkw/input$export",
        smartup_method="POST",
        smartup_object="input",
        target_table="warehouse_receipts",
        target_entity="Receipts to warehouse",
        sync_mode="incremental",
        key_fields=("input_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("input_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Purchase export",
        group="operations",
        smartup_endpoint="/b/anor/mxsx/mkw/purchase$export",
        smartup_method="POST",
        smartup_object="purchase",
        target_table="purchases",
        target_entity="Purchase",
        sync_mode="incremental",
        key_fields=("purchase_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("purchase_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Inventory balance",
        group="inventory",
        smartup_endpoint="/b/anor/mxsx/mkw/balance$export",
        smartup_method="POST",
        smartup_object="balance",
        target_table="inventory_balances",
        target_entity="Inventory balance snapshot",
        sync_mode="snapshot",
        key_fields=("warehouse_code", "product_code", "date"),
        field_mappings=(
            SmartUpFieldMapping("warehouse_code", "warehouse.external_ref"),
            SmartUpFieldMapping("product_code", "product.external_ref"),
            SmartUpFieldMapping("quantity", "quantity"),
            SmartUpFieldMapping("input_price", "input_price"),
            SmartUpFieldMapping("inventory_kind", "metadata.inventory_kind"),
            SmartUpFieldMapping("batch_number", "metadata.batch_number"),
        ),
        notes=("This is the main source for stock dashboard, availability, and replenishment.",),
    ),
    SmartUpMapping(
        name="Equipment balance",
        group="assets",
        smartup_endpoint="/b/trade/txs/tvt/equipment_balance$export_data",
        smartup_method="POST",
        smartup_object="data",
        target_table="equipment_assets",
        target_entity="Equipment asset snapshot",
        sync_mode="snapshot",
        key_fields=("person_id", "serial_number"),
        field_mappings=(
            SmartUpFieldMapping("person_id", "contact.external_ref"),
            SmartUpFieldMapping("person_code", "contact.external_ref"),
            SmartUpFieldMapping("serial_number", "external_ref"),
            SmartUpFieldMapping("equipment_status", "metadata.status"),
            SmartUpFieldMapping("installed_date", "metadata.installed_at"),
            SmartUpFieldMapping("last_visit_date", "metadata.last_visit_at"),
            SmartUpFieldMapping("lat_lng", "metadata.lat_lng"),
        ),
    ),
    SmartUpMapping(
        name="Movement export",
        group="assets",
        smartup_endpoint="/b/anor/mxsx/mqpf/equipment_movement$export",
        smartup_method="POST",
        smartup_object="equipment_movement",
        target_table="equipment_movements",
        target_entity="Equipment movement",
        sync_mode="incremental",
        key_fields=("movement_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("movement_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Request export",
        group="assets",
        smartup_endpoint="/b/anor/mxsx/mqpf/equipment_request$export",
        smartup_method="POST",
        smartup_object="equipment_request",
        target_table="equipment_requests",
        target_entity="Equipment request",
        sync_mode="incremental",
        key_fields=("request_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("request_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("status", "metadata.status"),
            SmartUpFieldMapping("created_on", "metadata.created_on"),
            SmartUpFieldMapping("modified_on", "metadata.modified_on"),
        ),
    ),
    SmartUpMapping(
        name="Visits",
        group="operations",
        smartup_endpoint="/b/trade/txs/tvt/visit$export",
        smartup_method="POST",
        smartup_object="visit",
        target_table="field_visits",
        target_entity="Field visit",
        sync_mode="incremental",
        key_fields=("visit_id", "external_id"),
        field_mappings=(
            SmartUpFieldMapping("visit_id", "external_ref"),
            SmartUpFieldMapping("external_id", "external_ref"),
            SmartUpFieldMapping("person_code", "contact.external_ref"),
            SmartUpFieldMapping("visit_date", "occurred_at"),
            SmartUpFieldMapping("visit_status", "metadata.status"),
            SmartUpFieldMapping("is_planned", "metadata.is_planned"),
            SmartUpFieldMapping("user_id", "metadata.user_id"),
        ),
        notes=("Supports sales force activity analysis and visit adherence reporting.",),
    ),
)


def get_smartup_mapping(name: str) -> SmartUpMapping | None:
    """Return a mapping by human-readable name."""

    return next((mapping for mapping in SMARTUP_CORE_MAPPING_V1 if mapping.name == name), None)


def get_smartup_mappings_by_group(group: str) -> list[SmartUpMapping]:
    """Return all mappings in a given functional group."""

    return [mapping for mapping in SMARTUP_CORE_MAPPING_V1 if mapping.group == group]
