"""Normalized Meta source tables and AI-safe projections."""

META_TABLES = {
    "meta_connections": (
        "id",
        "status",
        "meta_user_id",
        "meta_user_name",
        "created_at",
        "updated_at",
        "last_success_at",
        "last_error",
    ),
    "meta_resource_mappings": (
        "id",
        "organization_id",
        "resource_type",
        "external_id",
        "display_name",
        "connection_id",
        "created_at",
        "updated_at",
    ),
    "meta_ad_accounts": (
        "id",
        "organization_id",
        "connection_id",
        "external_id",
        "name",
        "currency",
        "timezone",
        "status",
        "created_at",
        "updated_at",
    ),
    "meta_campaigns": (
        "id",
        "organization_id",
        "ad_account_id",
        "external_id",
        "name",
        "status",
        "effective_status",
        "objective",
        "buying_type",
        "start_at",
        "stop_at",
        "created_at",
        "updated_at",
    ),
    "meta_ad_sets": (
        "id",
        "organization_id",
        "ad_account_id",
        "campaign_id",
        "external_id",
        "name",
        "status",
        "optimization_goal",
        "billing_event",
        "bid_strategy",
        "daily_budget",
        "lifetime_budget",
        "start_at",
        "end_at",
        "created_at",
        "updated_at",
    ),
    "meta_ads": (
        "id",
        "organization_id",
        "ad_account_id",
        "campaign_id",
        "ad_set_id",
        "external_id",
        "name",
        "status",
        "creative_id",
        "created_at",
        "updated_at",
    ),
    "meta_ads_insights_daily": (
        "id",
        "organization_id",
        "ad_account_id",
        "entity_type",
        "entity_external_id",
        "date_start",
        "date_stop",
        "breakdown_key",
        "breakdown_value",
        "currency",
        "spend",
        "impressions",
        "reach",
        "frequency",
        "clicks",
        "unique_clicks",
        "ctr",
        "cpc",
        "cpm",
        "created_at",
        "updated_at",
    ),
    "meta_ads_insight_actions": (
        "id",
        "insight_id",
        "action_type",
        "value",
        "action_value",
        "cost_per_action",
        "created_at",
        "updated_at",
    ),
    "meta_instagram_accounts": (
        "id",
        "organization_id",
        "connection_id",
        "external_id",
        "username",
        "name",
        "created_at",
        "updated_at",
    ),
    "meta_instagram_media": (
        "id",
        "organization_id",
        "account_id",
        "external_id",
        "media_type",
        "media_product_type",
        "caption",
        "permalink",
        "published_at",
        "shortcode",
        "created_at",
        "updated_at",
    ),
    "meta_instagram_media_insights_daily": (
        "id",
        "organization_id",
        "account_id",
        "media_id",
        "date_start",
        "date_stop",
        "reach",
        "impressions",
        "views",
        "likes",
        "comments",
        "shares",
        "saves",
        "interactions",
        "created_at",
        "updated_at",
    ),
    "meta_facebook_pages": (
        "id",
        "organization_id",
        "connection_id",
        "external_id",
        "name",
        "category",
        "instagram_account_id",
        "created_at",
        "updated_at",
    ),
    "meta_facebook_posts": (
        "id",
        "organization_id",
        "page_id",
        "external_id",
        "message",
        "permalink",
        "published_at",
        "created_at",
        "updated_at",
    ),
    "meta_facebook_post_insights_daily": (
        "id",
        "organization_id",
        "page_id",
        "post_id",
        "date_start",
        "date_stop",
        "reach",
        "impressions",
        "engaged_users",
        "reactions",
        "comments",
        "shares",
        "created_at",
        "updated_at",
    ),
    "meta_sync_runs": (
        "id",
        "connection_id",
        "status",
        "mode",
        "started_at",
        "finished_at",
        "last_error",
        "created_at",
        "updated_at",
    ),
}

_META_UNIQUES = {
    "meta_resource_mappings": "UNIQUE (organization_id, resource_type, external_id)",
    "meta_ad_accounts": "UNIQUE (connection_id, external_id)",
    "meta_campaigns": "UNIQUE (organization_id, ad_account_id, external_id)",
    "meta_ad_sets": "UNIQUE (organization_id, ad_account_id, external_id)",
    "meta_ads": "UNIQUE (organization_id, ad_account_id, external_id)",
    "meta_ads_insights_daily": "UNIQUE (organization_id, ad_account_id, entity_type, entity_external_id, date_start, date_stop, breakdown_key, breakdown_value)",
    "meta_ads_insight_actions": "UNIQUE (insight_id, action_type)",
    "meta_instagram_accounts": "UNIQUE (connection_id, external_id)",
    "meta_instagram_media": "UNIQUE (organization_id, account_id, external_id)",
    "meta_instagram_media_insights_daily": "UNIQUE (organization_id, account_id, media_id, date_start, date_stop)",
    "meta_facebook_pages": "UNIQUE (connection_id, external_id)",
    "meta_facebook_posts": "UNIQUE (organization_id, page_id, external_id)",
    "meta_facebook_post_insights_daily": "UNIQUE (organization_id, page_id, post_id, date_start, date_stop)",
}

META_DDL = tuple(
    f"CREATE TABLE IF NOT EXISTS {table} ("
    + ", ".join(
        f"{column} {'uuid' if column in {'id', 'connection_id', 'organization_id', 'ad_account_id', 'campaign_id', 'ad_set_id', 'ad_set_id', 'insight_id', 'account_id', 'media_id', 'page_id', 'post_id'} else 'text'}"
        for column in columns
    )
    + ", PRIMARY KEY (id)"
    + (f", {_META_UNIQUES[table]}" if table in _META_UNIQUES else "")
    + ")"
    for table, columns in META_TABLES.items()
)

# Explicit typed columns are published; credentials and opaque API payloads are not.
META_VIEW_DEFINITIONS = {
    "ai_meta_ad_accounts": "SELECT organization_id, id, external_id, name, currency, timezone, status FROM meta_ad_accounts",
    "ai_meta_campaigns": "SELECT organization_id, id, ad_account_id, external_id, name, status, effective_status, objective, buying_type, start_at, stop_at FROM meta_campaigns",
    "ai_meta_adsets": "SELECT organization_id, id, ad_account_id, campaign_id, external_id, name, status, optimization_goal, billing_event, bid_strategy, daily_budget, lifetime_budget, start_at, end_at FROM meta_ad_sets",
    "ai_meta_ads": "SELECT organization_id, ad_account_id, campaign_id, ad_set_id, external_id, name, status, creative_id FROM meta_ads",
    "ai_meta_ads_daily": "SELECT organization_id, ad_account_id, entity_type, entity_external_id, date_start, date_stop, breakdown_key, breakdown_value, currency, spend, impressions, reach, frequency, clicks, unique_clicks, ctr, cpc, cpm FROM meta_ads_insights_daily",
    "ai_instagram_accounts": "SELECT organization_id, id, external_id, username, name FROM meta_instagram_accounts",
    "ai_instagram_media": "SELECT organization_id, account_id, external_id, media_type, media_product_type, caption, permalink, published_at, shortcode FROM meta_instagram_media",
    "ai_instagram_media_daily": "SELECT organization_id, account_id, media_id, date_start, date_stop, reach, impressions, views, likes, comments, shares, saves, interactions FROM meta_instagram_media_insights_daily",
    "ai_facebook_pages": "SELECT organization_id, id, external_id, name, category, instagram_account_id FROM meta_facebook_pages",
    "ai_facebook_posts": "SELECT organization_id, page_id, external_id, message, permalink, published_at FROM meta_facebook_posts",
    "ai_facebook_posts_daily": "SELECT organization_id, page_id, post_id, date_start, date_stop, reach, impressions, engaged_users, reactions, comments, shares FROM meta_facebook_post_insights_daily",
}
META_VIEW_COLUMNS = {
    name: tuple(
        part.strip().split(" AS ")[-1]
        for part in select.split("SELECT ", 1)[1].split(" FROM ", 1)[0].split(",")
    )
    for name, select in META_VIEW_DEFINITIONS.items()
}

META_SQLITE_DDL = META_DDL
